package lab6;

// @author CASTRO TOCAFFONDI Alexander Piero

public class Principal extends javax.swing.JFrame {
    Empleado e;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCodigo = new javax.swing.JTextField();
        jNombre = new javax.swing.JTextField();
        jSueldoBase = new javax.swing.JTextField();
        jHExtras = new javax.swing.JTextField();
        jTipoSeguro = new javax.swing.JComboBox<>();
        jArea = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDatos = new javax.swing.JTextArea();
        jCrearObjeto = new javax.swing.JButton();
        jMostrarInfo = new javax.swing.JButton();
        jLimpiar = new javax.swing.JButton();
        jSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LABORATORIO 6");

        jCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Código"));

        jNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        jSueldoBase.setBorder(javax.swing.BorderFactory.createTitledBorder("Sueldo Base"));
        jSueldoBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSueldoBaseActionPerformed(evt);
            }
        });

        jHExtras.setBorder(javax.swing.BorderFactory.createTitledBorder("Horas Extras"));

        jTipoSeguro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECCIONE---", "AFP", "SNP" }));
        jTipoSeguro.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Seguro"));

        jArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---SELECCIONE---", "Sistemas", "Administración", "Marketing" }));
        jArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Area"));

        jDatos.setColumns(20);
        jDatos.setRows(5);
        jScrollPane1.setViewportView(jDatos);

        jCrearObjeto.setText("Crear Objeto");
        jCrearObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearObjetoActionPerformed(evt);
            }
        });

        jMostrarInfo.setText("Mostrar información del Objeto");
        jMostrarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMostrarInfoActionPerformed(evt);
            }
        });

        jLimpiar.setText("Limpiar");
        jLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpiarActionPerformed(evt);
            }
        });

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCrearObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jMostrarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSueldoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jHExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTipoSeguro, 0, 165, Short.MAX_VALUE)
                            .addComponent(jArea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTipoSeguro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSueldoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jHExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCrearObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMostrarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMostrarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMostrarInfoActionPerformed
        jDatos.append("Codigo: "+e.getCodigo()+"\n");
        jDatos.append("Nombre: "+e.getNombre()+"\n");
        jDatos.append("Seguro: "+e.getTipo_seg()+"\n");
        jDatos.append("Sueldo Base: "+e.getSueldoBase()+"\n");
        jDatos.append("Horas Extras: "+e.getHorasExtras()+"\n");
        jDatos.append("Area: "+e.getArea()+"\n");
        jDatos.append("Monto Extra: "+e.montoHExtras()+"\n");
        jDatos.append("Monto Seguro: "+e.montoSeguro()+"\n");
        jDatos.append("Monto EsSalud: "+e.montoEssalud()+"\n");
        jDatos.append("Monto de Descuentos: "+e.montoDescuentos()+"\n");
        jDatos.append("Sueldo Bruto: "+e.sueldoBruto()+"\n");
        jDatos.append("SueldoNeto: "+e.sueldoNeto()+"\n");
    }//GEN-LAST:event_jMostrarInfoActionPerformed

    private void jLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpiarActionPerformed
        jCodigo.setText("");
        jNombre.setText("");
        jTipoSeguro.setSelectedIndex(0);
        jSueldoBase.setText("");
        jHExtras.setText("");
        jArea.setSelectedIndex(0);
        jDatos.setText("");
        jCodigo.setText("");
        
    }//GEN-LAST:event_jLimpiarActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jSalirActionPerformed

    private void jCrearObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearObjetoActionPerformed
        String cod      = jCodigo.getText();
        String nom      = jNombre.getText();
        String seguro   = jTipoSeguro.getSelectedItem().toString();
        double sueldo   = Double.parseDouble(jSueldoBase.getText());
        double h_extras = Double.parseDouble(jHExtras.getText());
        String area     = jArea.getSelectedItem().toString();
        
        e=new Empleado(cod,nom,area,sueldo,h_extras,seguro);
    }//GEN-LAST:event_jCrearObjetoActionPerformed

    private void jSueldoBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSueldoBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSueldoBaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jArea;
    private javax.swing.JTextField jCodigo;
    private javax.swing.JButton jCrearObjeto;
    private javax.swing.JTextArea jDatos;
    private javax.swing.JTextField jHExtras;
    private javax.swing.JButton jLimpiar;
    private javax.swing.JButton jMostrarInfo;
    private javax.swing.JTextField jNombre;
    private javax.swing.JButton jSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSueldoBase;
    private javax.swing.JComboBox<String> jTipoSeguro;
    // End of variables declaration//GEN-END:variables
}
