/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CASTRO_TOCAFFONDI;

/**
 *
 * @author ADM667
 */
public class Game extends javax.swing.JFrame {
    Azar a;

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        jhead.setVisible(false);
        jhands.setVisible(false);
        jfooter.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLanzar = new javax.swing.JButton();
        jcaparazon = new javax.swing.JLabel();
        jhead = new javax.swing.JLabel();
        jhands = new javax.swing.JLabel();
        jfooter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(750, 600));

        jButton1.setText("Volver");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLanzar.setText("Lanzar dados");
        jLanzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLanzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLanzarMouseClicked(evt);
            }
        });
        jLanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLanzarActionPerformed(evt);
            }
        });

        jcaparazon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caparazon.png"))); // NOI18N
        jcaparazon.setFocusable(false);

        jhead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/head.png"))); // NOI18N

        jhands.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hands.png"))); // NOI18N

        jfooter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/footer.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jhead)
                    .addComponent(jhands)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(590, 590, 590)
                        .addComponent(jLanzar))
                    .addComponent(jfooter)
                    .addComponent(jcaparazon)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jhead)
                    .addComponent(jhands)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(jLanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jfooter)
                    .addComponent(jcaparazon)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        Iniciar i=new Iniciar();
        i.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLanzarActionPerformed
        int n1=a.getRamdon();
        int n2=a.getRamdon();
        
        a=new Azar(n1, n2);
        
        if(a.getN1()==1 && a.getN2()==1){
            jhead.setVisible(true);
        }
        if(a.getN1()==2 && a.getN2()==2){
            jhands.setVisible(true);
        }
        if(a.getN1()==4 && a.getN2()==4){
            jfooter.setVisible(true);
        }
        /*jhead.revalidate();
        jhead.repaint();
        jhands.revalidate();
        jhands.repaint();
        jfooter.revalidate();
        jfooter.repaint();*/
        //JOptionPane.showMessageDialog(null, "Resultado: ","RESULTADO",JOptionPane.INFORMATION_MESSAGE);
        a.Resultado();
    }//GEN-LAST:event_jLanzarActionPerformed

    private void jLanzarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLanzarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLanzarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jLanzar;
    private javax.swing.JLabel jcaparazon;
    private javax.swing.JLabel jfooter;
    private javax.swing.JLabel jhands;
    private javax.swing.JLabel jhead;
    // End of variables declaration//GEN-END:variables

}
