/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CASTRO_TOCAFFONDI;

/**
 *
 * @author ADM667
 */
public class Game extends javax.swing.JFrame {
    Azar a;

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        jhead.setVisible(false);
        jhands.setVisible(false);
        jfooter.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLanzar = new javax.swing.JButton();
        jhands = new javax.swing.JLabel();
        jcaparazon = new javax.swing.JLabel();
        jhead = new javax.swing.JLabel();
        jfooter = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setText("Volver");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLanzar.setText("Lanzar dados");
        jLanzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLanzarActionPerformed(evt);
            }
        });

        jhands.setBackground(new java.awt.Color(0, 0, 51));
        jhands.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jhands.setForeground(new java.awt.Color(255, 255, 255));
        jhands.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jhands.setOpaque(true);

        jcaparazon.setBackground(new java.awt.Color(0, 0, 51));
        jcaparazon.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jcaparazon.setForeground(new java.awt.Color(255, 255, 255));
        jcaparazon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jcaparazon.setOpaque(true);

        jhead.setBackground(new java.awt.Color(0, 0, 51));
        jhead.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jhead.setForeground(new java.awt.Color(255, 255, 255));
        jhead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jhead.setOpaque(true);

        jfooter.setBackground(new java.awt.Color(0, 0, 51));
        jfooter.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jfooter.setForeground(new java.awt.Color(255, 255, 255));
        jfooter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jfooter.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcaparazon, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jfooter, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jhands, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jhead, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(128, 128, 128))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLanzar)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jfooter, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jhands, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jcaparazon, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jhead, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        Iniciar i=new Iniciar();
        i.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLanzarActionPerformed
        int n1=a.getRamdon();
        int n2=a.getRamdon();
        
        a=new Azar(n1, n2);
        
        if(a.getN1()==1 && a.getN2()==1){
            jhead.setVisible(true);
        }
        if(a.getN1()==2 && a.getN2()==2){
            jhands.setVisible(true);
        }
        if(a.getN1()==4 && a.getN2()==4){
            jfooter.setVisible(true);
        }
        /*jhead.revalidate();
        jhead.repaint();
        jhands.revalidate();
        jhands.repaint();
        jfooter.revalidate();
        jfooter.repaint();*/
        //JOptionPane.showMessageDialog(null, "Resultado: ","RESULTADO",JOptionPane.INFORMATION_MESSAGE);
        a.Resultado();
    }//GEN-LAST:event_jLanzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jLanzar;
    private javax.swing.JLabel jcaparazon;
    private javax.swing.JLabel jfooter;
    private javax.swing.JLabel jhands;
    private javax.swing.JLabel jhead;
    // End of variables declaration//GEN-END:variables

}
